
version: '3'

services:

  inspire:
    image: catone/inspire:server
    container_name: inspire_flask

    links:
      - redis

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: python3 ./inspire.py


  redis:
    image: redis:latest
    container_name: inspire_redis


  nginx:
    image: catone/inspire:nginx
    links:
      - inspire
    ports:
      - 9010:80
      - 8888:81
    volumes:
      - type: bind
        source: /var/super-inspire-frontend/build
        target: /var/

    container_name: inspire_nginx
