

version: '1'

services:

  inspire:
    image: catone/inspire:server
    container_name: inspire_flask

    links:
      - redis
    environment:
      SERVERURL: 115.238.228.39
      SERVERPORT: 65501      
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
    command: python3 ./inspire.py


  redis:
    image: redisInstance
    container_name: inspire_redis


  nginx:
    image: catone/inspire:nginx
    links:
      - inspire
    ports:
      - 9010:80

    container_name: inspire_nginx

